name: Data Extractor

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up config
        run: echo "CONFIG=$(jq -c . < dependents.json)" >> $GITHUB_ENV

      - name: Run dependents-tracker extractor
        run: npx @dependents-tracker/extractor '${{fromJson(env.CONFIG).owner}}/${{ fromJson(env.CONFIG).package }}' '${{ fromJson(env.CONFIG).path }}/${{ fromJson(env.CONFIG).package}}.json'

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git pull
          git add ${{ fromJson(env.CONFIG).path }}/${{ fromJson(env.CONFIG).package }}.json
          git commit -m "Update dependents data $(date +'%Y-%m-%d')"
          git push
